import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Meu gato atelie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
           Atelie  MEU GATO!
            <code className={styles.code}></code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
             andrecorreiadev
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/caragato.jpg"
            alt="Next.js Logo"
            width={180}
            height={180}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="/produtos"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Produtos <span>-&gt;</span>
            </h2>
            <p>
              Os melhores produtos.sempre!
            </p>
          </a>

          <a
            href="/servicos"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Servicos <span>-&gt;</span>
            </h2>
            <p>
              Conheca nossos servicos. E surpreeda-se!
            </p>
          </a>

          <a
            href="/contatos"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Contatos <span>-&gt;</span>
            </h2>
            <p>
              Entre em contato conosco nas redes sociais.
            </p>
          </a>

          <a
            href="/quemsomos"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Quem somos <span>-&gt;</span>
            </h2>
           <p>
           Conheca nosso trabalho.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
